# Music file names normalizer
# This is start file
# Developed by https://github.com/Annndruha
# 2020

if __name__ == '__main__':
    try:
        from PyQt5 import QtWidgets
        import traceback
        import sys
        import datetime
        import os
        from implementation import MainWindow

        app = QtWidgets.QApplication([])
        application = MainWindow()
        application.show()
        app.exec()

    except:
        try:
            stamp = f"Crash {str(datetime.datetime.strftime(datetime.datetime.now(), '%Y.%m.%d %H.%M.%S'))}.txt"
            with open(stamp,"w+") as f:
                f.write("--This file generated by Music files normalizer--\n\n")
                f.write(str(traceback.format_exc()))
        except Exception as err:
            print(err)
            print(err.args)
