# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(840, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 168, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 168, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 253, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(168, 168, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 126, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setMinimumSize(QtCore.QSize(840, 500))
        self.widget.setMaximumSize(QtCore.QSize(1600, 500))
        self.widget.setObjectName("widget")
        self.label_program_name = QtWidgets.QLabel(self.widget)
        self.label_program_name.setGeometry(QtCore.QRect(220, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_program_name.setFont(font)
        self.label_program_name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_program_name.setScaledContents(False)
        self.label_program_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_program_name.setObjectName("label_program_name")
        self.group_names = QtWidgets.QGroupBox(self.widget)
        self.group_names.setGeometry(QtCore.QRect(10, 160, 341, 331))
        self.group_names.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.group_names.setObjectName("group_names")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.group_names)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 291))
        self.verticalLayoutWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.name_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.name_layout.setObjectName("name_layout")
        self.checkBox_mp3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_mp3.setFont(font)
        self.checkBox_mp3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_mp3.setChecked(True)
        self.checkBox_mp3.setObjectName("checkBox_mp3")
        self.name_layout.addWidget(self.checkBox_mp3)
        self.checkBox_brackets = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_brackets.setFont(font)
        self.checkBox_brackets.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_brackets.setChecked(True)
        self.checkBox_brackets.setObjectName("checkBox_brackets")
        self.name_layout.addWidget(self.checkBox_brackets)
        self.checkBox_underscore = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_underscore.setFont(font)
        self.checkBox_underscore.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_underscore.setChecked(True)
        self.checkBox_underscore.setObjectName("checkBox_underscore")
        self.name_layout.addWidget(self.checkBox_underscore)
        self.checkBox_doublespace = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_doublespace.setFont(font)
        self.checkBox_doublespace.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_doublespace.setChecked(True)
        self.checkBox_doublespace.setObjectName("checkBox_doublespace")
        self.name_layout.addWidget(self.checkBox_doublespace)
        self.checkBox_samename = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_samename.setFont(font)
        self.checkBox_samename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_samename.setChecked(False)
        self.checkBox_samename.setObjectName("checkBox_samename")
        self.name_layout.addWidget(self.checkBox_samename)
        self.checkBox_user_replace = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_user_replace.setFont(font)
        self.checkBox_user_replace.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_user_replace.setObjectName("checkBox_user_replace")
        self.name_layout.addWidget(self.checkBox_user_replace)
        self.label_replace_to = QtWidgets.QLabel(self.group_names)
        self.label_replace_to.setEnabled(False)
        self.label_replace_to.setGeometry(QtCore.QRect(140, 290, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_replace_to.setFont(font)
        self.label_replace_to.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_replace_to.setAlignment(QtCore.Qt.AlignCenter)
        self.label_replace_to.setObjectName("label_replace_to")
        self.lineEdit_from = QtWidgets.QLineEdit(self.group_names)
        self.lineEdit_from.setEnabled(False)
        self.lineEdit_from.setGeometry(QtCore.QRect(20, 290, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_from.setFont(font)
        self.lineEdit_from.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_from.setObjectName("lineEdit_from")
        self.lineEdit_to = QtWidgets.QLineEdit(self.group_names)
        self.lineEdit_to.setEnabled(False)
        self.lineEdit_to.setGeometry(QtCore.QRect(200, 290, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_to.setFont(font)
        self.lineEdit_to.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.group_file_open = QtWidgets.QGroupBox(self.widget)
        self.group_file_open.setGeometry(QtCore.QRect(10, 50, 821, 101))
        self.group_file_open.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.group_file_open.setObjectName("group_file_open")
        self.pushButton_path = QtWidgets.QPushButton(self.group_file_open)
        self.pushButton_path.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.pushButton_path.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_path.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_path.setIcon(icon1)
        self.pushButton_path.setObjectName("pushButton_path")
        self.check_include_subfolder = QtWidgets.QCheckBox(self.group_file_open)
        self.check_include_subfolder.setGeometry(QtCore.QRect(50, 70, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_include_subfolder.setFont(font)
        self.check_include_subfolder.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.check_include_subfolder.setChecked(True)
        self.check_include_subfolder.setObjectName("check_include_subfolder")
        self.lineEdit_filepath = QtWidgets.QLineEdit(self.group_file_open)
        self.lineEdit_filepath.setGeometry(QtCore.QRect(50, 30, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_filepath.setFont(font)
        self.lineEdit_filepath.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.group_options = QtWidgets.QGroupBox(self.widget)
        self.group_options.setGeometry(QtCore.QRect(360, 280, 271, 161))
        self.group_options.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.group_options.setObjectName("group_options")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.group_options)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 253, 131))
        self.verticalLayoutWidget_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.options_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.options_layout.setObjectName("options_layout")
        self.radioButton_dialog = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_dialog.setFont(font)
        self.radioButton_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_dialog.setChecked(True)
        self.radioButton_dialog.setObjectName("radioButton_dialog")
        self.options_layout.addWidget(self.radioButton_dialog)
        self.radioButton_all = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_all.setFont(font)
        self.radioButton_all.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.radioButton_all.setChecked(False)
        self.radioButton_all.setObjectName("radioButton_all")
        self.options_layout.addWidget(self.radioButton_all)
        self.radioButton_tag_manual = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_tag_manual.setFont(font)
        self.radioButton_tag_manual.setObjectName("radioButton_tag_manual")
        self.options_layout.addWidget(self.radioButton_tag_manual)
        self.radioButton_tag_auto = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_tag_auto.setFont(font)
        self.radioButton_tag_auto.setObjectName("radioButton_tag_auto")
        self.options_layout.addWidget(self.radioButton_tag_auto)
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setGeometry(QtCore.QRect(640, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_start.setObjectName("pushButton_start")
        self.group_tags = QtWidgets.QGroupBox(self.widget)
        self.group_tags.setGeometry(QtCore.QRect(360, 150, 471, 131))
        self.group_tags.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.group_tags.setObjectName("group_tags")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.group_tags)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 451, 101))
        self.verticalLayoutWidget_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.tags_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.tags_layout.setObjectName("tags_layout")
        self.checkBox_delete_tags = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_delete_tags.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_delete_tags.setFont(font)
        self.checkBox_delete_tags.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_delete_tags.setChecked(False)
        self.checkBox_delete_tags.setObjectName("checkBox_delete_tags")
        self.tags_layout.addWidget(self.checkBox_delete_tags)
        self.checkBox_set_artist_tag = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_set_artist_tag.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_set_artist_tag.setFont(font)
        self.checkBox_set_artist_tag.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_set_artist_tag.setChecked(False)
        self.checkBox_set_artist_tag.setObjectName("checkBox_set_artist_tag")
        self.tags_layout.addWidget(self.checkBox_set_artist_tag)
        self.checkBox_set_song_tag = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_set_song_tag.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_set_song_tag.setFont(font)
        self.checkBox_set_song_tag.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_set_song_tag.setChecked(False)
        self.checkBox_set_song_tag.setObjectName("checkBox_set_song_tag")
        self.tags_layout.addWidget(self.checkBox_set_song_tag)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(360, 450, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label__autor = QtWidgets.QLabel(self.widget)
        self.label__autor.setGeometry(QtCore.QRect(640, 26, 101, 20))
        self.label__autor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label__autor.setOpenExternalLinks(True)
        self.label__autor.setObjectName("label__autor")
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit_log.setGeometry(QtCore.QRect(850, 10, 741, 471))
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setCenterOnScroll(True)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.checkBox_logs = QtWidgets.QCheckBox(self.widget)
        self.checkBox_logs.setGeometry(QtCore.QRect(640, 330, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_logs.setFont(font)
        self.checkBox_logs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.checkBox_logs.setChecked(False)
        self.checkBox_logs.setObjectName("checkBox_logs")
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_path, self.check_include_subfolder)
        MainWindow.setTabOrder(self.check_include_subfolder, self.checkBox_mp3)
        MainWindow.setTabOrder(self.checkBox_mp3, self.checkBox_brackets)
        MainWindow.setTabOrder(self.checkBox_brackets, self.checkBox_underscore)
        MainWindow.setTabOrder(self.checkBox_underscore, self.checkBox_doublespace)
        MainWindow.setTabOrder(self.checkBox_doublespace, self.checkBox_user_replace)
        MainWindow.setTabOrder(self.checkBox_user_replace, self.checkBox_delete_tags)
        MainWindow.setTabOrder(self.checkBox_delete_tags, self.checkBox_set_artist_tag)
        MainWindow.setTabOrder(self.checkBox_set_artist_tag, self.checkBox_set_song_tag)
        MainWindow.setTabOrder(self.checkBox_set_song_tag, self.radioButton_all)
        MainWindow.setTabOrder(self.radioButton_all, self.pushButton_start)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music file names normalizer"))
        self.label_program_name.setText(_translate("MainWindow", "Music file names normalizer"))
        self.group_names.setTitle(_translate("MainWindow", "Name editor"))
        self.checkBox_mp3.setText(_translate("MainWindow", "Replace \".mp3.mp3\" to \".mp3\""))
        self.checkBox_brackets.setText(_translate("MainWindow", "Delete brackets (smth), [smth]"))
        self.checkBox_underscore.setText(_translate("MainWindow", "Smart underscore replace"))
        self.checkBox_doublespace.setText(_translate("MainWindow", "Correct dashs and doublespace"))
        self.checkBox_samename.setText(_translate("MainWindow", "Delete if file have same filename"))
        self.checkBox_user_replace.setText(_translate("MainWindow", "User replace:"))
        self.label_replace_to.setText(_translate("MainWindow", "to"))
        self.group_file_open.setTitle(_translate("MainWindow", "Select folder"))
        self.check_include_subfolder.setText(_translate("MainWindow", "Include subfolders"))
        self.group_options.setTitle(_translate("MainWindow", "Options"))
        self.radioButton_dialog.setText(_translate("MainWindow", "Open manual rename dialog"))
        self.radioButton_all.setText(_translate("MainWindow", "Force rename"))
        self.radioButton_tag_manual.setText(_translate("MainWindow", "Open tags editor"))
        self.radioButton_tag_auto.setText(_translate("MainWindow", "Force delete and set tags"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.group_tags.setTitle(_translate("MainWindow", "Tags"))
        self.checkBox_delete_tags.setText(_translate("MainWindow", "Delete all tags"))
        self.checkBox_set_artist_tag.setText(_translate("MainWindow", "Set new Artist-tag as part before \" - \""))
        self.checkBox_set_song_tag.setText(_translate("MainWindow", "Set new Song-name-tag as part after \" - \""))
        self.label__autor.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/Annndruha\"><span style=\" color:#000000;\">by Annndruha</span></a></p></body></html>"))
        self.plainTextEdit_log.setPlaceholderText(_translate("MainWindow", "Logs"))
        self.checkBox_logs.setText(_translate("MainWindow", "Show info"))

